# Generated by Django 5.2.17 on 2026-09-29 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StructuralAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("asset_name", models.CharField(db_index=True, max_length=160)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("BRIDGE", "Bridge"),
                            ("ROAD", "Road"),
                            ("BUILDING", "Building"),
                            ("TUNNEL", "Tunnel"),
                            ("TOWER", "Tower"),
                            ("DAM", "Dam"),
                            ("INDUSTRIAL", "Industrial Structure"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("REINFORCED_CONCRETE", "Reinforced Concrete"),
                            ("PRESTRESSED_CONCRETE", "Prestressed Concrete"),
                            ("STRUCTURAL_STEEL", "Structural Steel"),
                            ("MASONRY", "Masonry"),
                            ("ASPHALT", "Asphalt"),
                            ("TIMBER", "Timber"),
                            ("COMPOSITE", "Composite"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Human readable location, e.g. city / corridor.",
                        max_length=200,
                    ),
                ),
                ("region", models.CharField(blank=True, db_index=True, max_length=80)),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "structural_system",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Box girder, Portal frame",
                        max_length=120,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 420 m x 18 m, 4 lanes",
                        max_length=120,
                    ),
                ),
                ("operator", models.CharField(blank=True, max_length=120)),
                ("inspection_interval_days", models.PositiveIntegerField(default=180)),
                (
                    "current_health_score",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "last_inspection_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ("asset_name",),
            },
        ),
    ]
