# Generated by Django 5.2.17 on 2026-09-29 07:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefectDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        choices=[
                            ("CRACK", "Concrete crack"),
                            ("SPALLING", "Spalling"),
                            ("CORROSION", "Corrosion"),
                            ("RUST", "Rust staining"),
                            ("EXPOSED_REBAR", "Exposed rebar"),
                            ("EFFLORESCENCE", "Efflorescence"),
                            ("SURFACE_DAMAGE", "Surface damage"),
                            ("DEFORMATION", "Deformation"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("x_min", models.PositiveIntegerField()),
                ("y_min", models.PositiveIntegerField()),
                ("x_max", models.PositiveIntegerField()),
                ("y_max", models.PositiveIntegerField()),
                (
                    "area_ratio",
                    models.FloatField(
                        default=0,
                        help_text="Bounding-box area relative to the image area.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("UNREVIEWED", "Unreviewed"),
                            ("CONFIRMED", "Confirmed by engineer"),
                            ("REJECTED", "Rejected (false positive)"),
                        ],
                        default="UNREVIEWED",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-confidence_score",),
            },
        ),
        migrations.CreateModel(
            name="ImageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        help_text="Canonical object location (s3:// or file://).",
                        max_length=500,
                    ),
                ),
                ("storage_key", models.CharField(max_length=300)),
                ("thumbnail_key", models.CharField(blank=True, max_length=300)),
                ("preview_key", models.CharField(blank=True, max_length=300)),
                ("annotated_key", models.CharField(blank=True, max_length=300)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveBigIntegerField()),
                ("image_width", models.PositiveIntegerField()),
                ("image_height", models.PositiveIntegerField()),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the uploaded bytes.",
                        max_length=64,
                    ),
                ),
                ("health_score", models.FloatField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("uploaded_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="InspectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine visual"),
                            ("DRONE", "Drone survey"),
                            ("FIXED_CAMERA", "Fixed camera"),
                            ("DETAILED", "Detailed structural"),
                            ("POST_EVENT", "Post-event (storm / seismic)"),
                            ("FOLLOW_UP", "Follow-up"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "processing_stage",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("STORED", "Stored"),
                            ("QUEUED", "Queued"),
                            ("PREPROCESSING", "Preprocessing"),
                            ("INFERENCE", "AI inference"),
                            ("ANALYZING", "Analyzing defects"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADING",
                        max_length=16,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "overall_health_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("defect_count", models.PositiveIntegerField(default=0)),
                (
                    "max_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Total worker processing time in seconds.",
                        null=True,
                    ),
                ),
                ("model_version", models.CharField(blank=True, max_length=120)),
                (
                    "inference_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("demo", "Demo (mock inference)"),
                            ("production", "Production model"),
                        ],
                        max_length=12,
                    ),
                ),
                ("preprocessing_report", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-inspection_date", "-id"),
            },
        ),
    ]
