# Generated by Django 5.2.17 on 2026-09-29 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0002_initial"),
        ("inspections", "0001_initial"),
        ("ml", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="defectdetection",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imagerecord",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="defectdetection",
            name="image_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="inspections.imagerecord",
            ),
        ),
        migrations.AddField(
            model_name="inspectionlog",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspectionlog",
            name="ml_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to="ml.mlmodel",
            ),
        ),
        migrations.AddField(
            model_name="inspectionlog",
            name="structural_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="assets.structuralasset",
            ),
        ),
        migrations.AddField(
            model_name="imagerecord",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inspections.inspectionlog",
            ),
        ),
        migrations.AddField(
            model_name="defectdetection",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="inspections.inspectionlog",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionlog",
            index=models.Index(
                fields=["structural_asset", "-inspection_date"],
                name="inspections_structu_0e3c2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionlog",
            index=models.Index(
                fields=["status", "-created_at"], name="inspections_status_7cae30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defectdetection",
            index=models.Index(
                fields=["defect_type", "severity"],
                name="inspections_defect__65ce66_idx",
            ),
        ),
    ]
