# Generated by Django 5.2.17 on 2026-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("DEFECT_DETECTED", "Defect detected"),
                            ("HEALTH_DECLINE", "Health decline"),
                            ("INSPECTION_OVERDUE", "Inspection overdue"),
                        ],
                        db_index=True,
                        default="DEFECT_DETECTED",
                        max_length=24,
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=14,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
