# Generated by Django 5.2.17 on 2026-09-29 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(default="InfraVision Operations", max_length=120),
                ),
                (
                    "healthy_threshold",
                    models.FloatField(
                        default=75.0,
                        help_text="Assets scoring at or above this value are considered healthy.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "critical_threshold",
                    models.FloatField(
                        default=50.0,
                        help_text="Assets scoring below this value are considered critical.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "alert_min_severity",
                    models.CharField(
                        choices=[
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="HIGH",
                        help_text="Detections at or above this severity raise a maintenance alert.",
                        max_length=10,
                    ),
                ),
                (
                    "alert_min_confidence",
                    models.FloatField(
                        default=0.6,
                        help_text="Detections below this model confidence never raise alerts on their own.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "health_drop_alert_points",
                    models.FloatField(
                        default=10.0,
                        help_text="Raise a health-decline alert when a score drops by at least this many points.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "default_inspection_interval_days",
                    models.PositiveIntegerField(default=180),
                ),
                ("auto_alerts_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "platform configuration",
                "verbose_name_plural": "platform configuration",
            },
        ),
    ]
