# Generated by Django 5.2.17 on 2026-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("version", models.CharField(max_length=60)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("PYTORCH", "PyTorch"),
                            ("TENSORFLOW", "TensorFlow"),
                            ("ONNX", "ONNX Runtime"),
                            ("OPENCV", "OpenCV (classical CV)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("architecture", models.CharField(blank=True, max_length=120)),
                (
                    "task",
                    models.CharField(
                        default="Structural defect detection", max_length=80
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False,
                        help_text="Demo/mock inference - not a trained model.",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="Validation accuracy (0-1) from the model card.",
                        null=True,
                    ),
                ),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("training_dataset", models.CharField(blank=True, max_length=160)),
                ("classes", models.JSONField(blank=True, default=list)),
                ("input_size", models.PositiveIntegerField(blank=True, null=True)),
                ("artifact_uri", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STAGING", "Staging"),
                            ("INACTIVE", "Inactive"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="STAGING",
                        max_length=10,
                    ),
                ),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ML model",
                "ordering": ("-last_heartbeat_at", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_name", "version"), name="unique_model_version"
                    )
                ],
            },
        ),
    ]
